version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
        - npm install yarn -g  
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync build s3://differencebetween.john-shenk.com
      - aws cloudfront create-invalidation --distribution-id E15NRVHVPCUS7W --paths /index.html /static/*
      - aws s3 sync punchlines s3://differencebetween
